### ISSUE TITLE
Gives a 403 Error when trying to authenticate

### ISSUE THREAD

**Issue by kiwiluver75** [jamon/playmusic#1]
Tried using the example that is provided, but it keeps giving me a bad authentication error. My username and password are correct. Furthermore, I receive an email to my account notifying me of unauthorized access to my account. However, I am easily able to access my Google Music account from the python Unofficial Google Music API. Thanks.

**Comment by aml25** [comment]
Can confirm this is still the case.  @stanier 's solution works for me.  Definitely would feel better about myself if I could go back and turn security back on.

**Comment by jamon** [comment]
This shouldn't happen anymore.

**Comment by amozgachev** [comment]
Hello.

I still get:

```
Unable to get stream urlError: 403 error from server
```

Even with oAuth enabled.
