### ISSUE TITLE
What about OAuth authentication (with an already google connected user) ?

### ISSUE THREAD

**Issue by gumyn** [jamon/playmusic#10]

**Comment by jamon** [comment]
Looks like this might be working for the python guys.  I'll take another look.

we'll need to port: https://github.com/simon-weber/gpsoauth

**Comment by jamon** [comment]
This should be working now.

**Comment by michael-lumley** [comment]
It still requires a user to provide a password though, right? Is there any way to send a user to a google url to authorize the token without having to provide their password to a third party?

**Comment by jamon** [comment]
Not in any practical way that I've seen.  You could make the "login" request by hand, and get an "oauth" token, and provide that to the playmusic script, but that token has all the same rights to your account as your real login/password (except the ability to change your password).  It can be used to authorize tokens for all services.

I'm planning on doing some testing on how long the tokens created from the master token are valid.  Those tokens are limited in scope to the "sj" service (skyjam a.k.a. google play music), so there's a practical security benefit of being able to generate those and only provide that to the library, but it would get annoying if those are short-lived.

**Comment by michael-lumley** [comment]
Yeah, that's what I was afraid of. Pretty shitty use of oauth if it requires the user to provide a password, but I suppose google's left us no other choice by failing to expose a proper API.

**Comment by michael-lumley** [comment]
I'm trying to write my own login using XMLHttpRequest rather than https, but I'm getting blocked by the cross-origin policy (I think). How did you get around that?

**Comment by jamon** [comment]
What part are you trying to write?  the cross origin policy would likely prevent you from making a browser-only solution.  My solution is for node.js.

**Comment by michael-lumley** [comment]
I'm writing for node too, but I would prefer to use the XMLHttpRequest object to send my requests directly, rather than route them through the node https library, as you did. Ultimately I determined that XHR is going to get blocked by cross-domain stuff, so I just went back to https. :/

**Comment by jamon** [comment]
You can use a flash or java based library to make the connections for you,
I think a few solutions exist for that.
