### ISSUE TITLE
Possible to adapt to use in browser?

### ISSUE THREAD

**Issue by amicloud** [jamon/playmusic#104]
I have tried using this package in a React application and, while it works, I am running into issues with CORS. Is this something addressable, or is it just not possible due to CORS and the browser?

**Comment by jamon** [comment]
It's not possible to make it work directly via browser, because the library talks directly to google's servers.  That said, you could proxy it via a server to make a browser-based application that used it.

**Comment by amicloud** [comment]
I was afraid of that. I will try your suggestion. I was hoping to do everything in the browser, but oh well. Thanks!
