### ISSUE TITLE
getAllTracks max 1000

### ISSUE THREAD

**Issue by aml25** [jamon/playmusic#16]
getAllTracks() seems to return 1000 tracks maximum.  There's nothing noting in the API doc that this is the case.

**Comment by michael-lumley** [comment]
I'm having the same problem, any progress? Is it a cap on the number of responses sent by Google?

**Comment by michael-lumley** [comment]
It seems that the response sent by Google is capped at 1k songs, but that the data sent back includes 'nextPageToken' which I presume can be sent with subsequent requests to complete the library. I'm going to do some more digging.

**Comment by jamon** [comment]
That is correct.  I need to add support for getting the next page.  I've been busy, but I'll try to find some time to do that relatively soon.  Otherwise, if you'd like to add the method, I'll happily accept a pull request.  The python library this is based on is a great resource for implementations like that.

Thanks,
Jamon

**Comment by michael-lumley** [comment]
Sure. I'm working on it now. I'm not really great with git, and my solution will probably adding a dependence on a deferred library (probably Q). If you don't mind the dependency, I'll put the code here when I'm done and let you do as you like with it.

**Comment by jamon** [comment]
I prefer to keep to standards as much as possible, so if a Promise library is necessary, I'll implement it with 'es6-promise', as that follows the ES6 standard, and is natively supported in later node versions.

There's another pull request open to make the library more similar to typical node libraries in its callback structure (i.e. function(error, callback)) which I think will eventually need to be reconciled, as well--I'll likely implement a non-promise API, and wrap it with a promise one, or perhaps the other way around, so people can use whichever they prefer.

That said, feel free to implement this however you like if you're writing it--just wanted to make you aware of what the next version I put out will look like in case you want to stay in sync with that.  Either way, I appreciate your feedback and contributions.

Thanks,
Jamon

**Comment by michael-lumley** [comment]
Sure, thanks for maintaining the library - it looks quite useful. I am a hobbyist at best, so while I'd like to do whatever I can to contribute to the library, its probably better for me to leave the really heavy lifting to others.

**Comment by michael-lumley** [comment]
I can't seem to find the right key for the continuation token when submitting subsequent requests back to the server. Other ports seem to use the key "continuationToken" but this does not seem to be effective for me, and those other ports are pointing at different server endpoints. Any suggestions?

**Comment by michael-lumley** [comment]
Found it <a href="http://stackoverflow.com/questions/16638356/google-music-api-how-to-request-the-next-1000-songs">here</a>. Key is "start-token".

**Comment by michael-lumley** [comment]
Actually, it's easiest to forget about sending page tokens and simply send a query for "max-results." Here is the updated code (in coffeescript):

    getLibrary: (maxResults, success, error) ->
        that = this;
        this.request({
            method: "POST",
            url: this._baseURL + "trackfeed",
            contentType: "application/json"
            data: JSON.stringify({"max-results": maxResults})
            success: (data, res) ->
                that.success(success, JSON.parse(data), res)
            error: (data, err, res) ->
                that.error("error retrieving all tracks", data, err, res)
        })

**Comment by tautologistics** [comment]
Created PR to address this properly. I have a huge library and `max-results` is not a viable option.

**Comment by jamon** [comment]
Thank you for the pull request.  I've merged it and will do a release as soon as I can.
