### ISSUE TITLE
500 Error: An Unknown Error Occurred

### ISSUE THREAD

**Issue by michael-lumley** [jamon/playmusic#17]
All of my requests to the google servers are coming back with data, but also with a 500 Error and an "Unknown Error Occurred" description. Example:

```json
"error":{
    "status": 500,
    "message": "An unknown error occurred",
    "kind": "sj#playlistEntryList",
    "nextPageToken": "*token*"
    "data": {
        "items": [
        {
            "kind": "sj#playlistEntry",
            ...
```

This isn't causing any problems that I know of, but it is a curious behavior. Any idea what might be causing it?

**Comment by jamon** [comment]
Please give v2.0.0 a try and let me know if you're still having issues.  The api has changed a bit, but just the callbacks.

**Comment by jamon** [comment]
This should be fixed.  Let me know if it isn't.
