### ISSUE TITLE
Google Auth error

### ISSUE THREAD

**Issue by aml25** [jamon/playmusic#18]
When trying to run anything as of today using the library, I get hit with this in terminal:

`[Function] '\u001b[32m\'https://developers.google.com/accounts/docs/AuthForInstalledApps\\n\'\u001b[39m'`

When I follow the link I'm brought to a page which describes ClientLogin as being deprecated:
`Important: ClientLogin has been officially deprecated since April 20, 2012 and is now no longer available. Requests to ClientLogin will fail with a HTTP 404 response. We encourage you to migrate to OAuth 2.0 as soon as possible.`

**Comment by jamon** [comment]
Yeah, it seems they completely turned off ClientLogin in the past couple of days.  I was able to get up and running again last night with oauth, though.  I'll go ahead and push a beta version with oauth support, but I've still got some work to do to clean it up.

**Comment by aml25** [comment]
Oh wow, weird timing with their I/O going on.

That's awesome though that there's an OAuth option.  Would love to check
that out, even if messy.  Thanks for this package man!  I've been having a
ton of fun messing with it.

Adam Laskowitz
Experience Design Lead | Target Innovation Center
http://www.adamlaskowitz.com

**Comment by jamon** [comment]
Should be fixed now.   Thanks for the report!

**Comment by aml25** [comment]
Want to document it somewhere... After the latest push, I had to add `error` parameter in front of all my "getAlbum", "getArtist", "getTrack" callbacks.  Otherwise, the data returned is null.

**Comment by jamon** [comment]
Yeah, that was a change that was suggested, to bring it more inline with typical node.js libraries.  that was as of 2.0.  I'll make that note more prominent though.

Thanks!
