### ISSUE TITLE
Issue with GetStreamURL

### ISSUE THREAD

**Issue by CogginCreations** [jamon/playmusic#22]
Headers are messed up in the request:

Also in the search example I had to fix the request:

pm.getStreamUrl(**song.station.seed.trackId**, function (err, streamUrl) {

In Play.JS: **that._deviceId** does not exist as part of the object.
options: { headers: { "X-Device-ID": that._deviceId } }

_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at PlayMusic.request (C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:63:21)
    at PlayMusic.getStreamUrl (C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:276:10)

*Output of **that:***
{ _email: 'redacted@gmail.com',
  _password: 'redacted',
  _masterToken: undefined,
  _key:
   { init:
      { [Function]
        [length]: 0,
        [name]: '',
        [arguments]: null,
        [caller]: null,
        [prototype]: [Circular] },
     '$super':
      { init:
         { [Function]
           [length]: 1,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: [Circular] },
        toString:
         { [Function]
           [length]: 1,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: { [constructor]: [Circular] } },
        concat:
         { [Function]
           [length]: 1,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: { [constructor]: [Circular] } },
        clamp:
         { [Function]
           [length]: 0,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: { [constructor]: [Circular] } },
        clone:
         { [Function]
           [length]: 0,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: { [constructor]: [Circular] } },
        random:
         { [Function]
           [length]: 1,
           [name]: '',
           [arguments]: null,
           [caller]: null,
           [prototype]: { [constructor]: [Circular] } },
        '$super':
         { extend:
            { [Function]
              [length]: 1,
              [name]: '',
              [arguments]: null,
              [caller]: null,
              [prototype]: { [constructor]: [Circular] } },
           create:
            { [Function]
              [length]: 0,
              [name]: '',
              [arguments]: null,
              [caller]: null,
              [prototype]: { [constructor]: [Circular] } },
           init:
            { [Function]
              [length]: 0,
              [name]: '',
              [arguments]: null,
              [caller]: null,
              [prototype]: { [constructor]: [Circular] } },
           mixIn:
            { [Function]
              [length]: 1,
              [name]: '',
              [arguments]: null,
              [caller]: null,
              [prototype]: { [constructor]: [Circular] } },
           clone:
            { [Function]
              [length]: 0,
              [name]: '',
              [arguments]: null,
              [caller]: null,
              [prototype]: { [constructor]: [Circular] } } } },
     words:
      [ 859071845,
        926496819,
        758474085,
        908932145,
        876031329,
        1631073837,
        875836261,
        1630549554,
        1633838647,
        926168121,
        862205537,
        758276401,
        892154931,
        1717906785,
        1633903917,
        1698117685,
        909523250,
        926234677,
        167772160,
        [length]: 19 ],
     sigBytes: 73 },
  _token: 'REALLY_BIG_LONG_RETACTED_TOKEN'}

**Comment by jamon** [comment]
Have you used any mobile devices with your google play music account?  The library pretends it's an existing device, so if there isn't one, it won't work.  I'll look at the error handling around that, but that is my guess as to what's wrong.

**Comment by CogginCreations** [comment]
I have downloaded the google music app to my phone and logged in the the account that I am using in this application. I have played a few songs with the radio feature. Is there anything else necessary to do? I believe this just stems from _deviceId not being a property of the object you are referencing.

**Comment by jamon** [comment]
which version are you running?  did you install from git or just npm? if git, make sure you're up to date, if npm, could you let me know which version? (npm ls will tell you)

thanks!

**Comment by jamon** [comment]
if you're looking for where _deviceId comes from, it's inside of init, as a callback from _oauth on line 130:

```
                that._deviceId = devices[0].id.slice(2);
```

**Comment by CogginCreations** [comment]
I am using version 2.0.2 pulled using npm.  Here is my call for the function using your examples:

//playmusic test
var pm = new PlayMusic();

pm.login({ email: GOOGLE_EMAIL, password: GOOGLE_PASSWORD, androidId: GOOGLE_ANDROIDID }, function (err, resp) {
    console.log(err, resp);
});

pm.init({ email: GOOGLE_EMAIL, password: GOOGLE_PASSWORD }, function () {

    pm.search("bastille lost fire", 5, function (err, data) {
        if (err) return console.error(err);
        
        var song = data.entries.sort(function (a, b) {
            return a.score < b.score;
        }).shift();
        console.log(util.inspect(song, { depth: 10 }));
        //console.log(song.station.seed.trackId);
        pm.getStreamUrl(song.station.seed.trackId, function (err, streamUrl) {
            if (err) console.error(err);
            console.log(streamUrl);
        });
    });
});

**Comment by jamon** [comment]
try leaving off pm.login, that's for creating a token that you can use in future login attempts.  if you just call init with your user/pass, it should work

**Comment by CogginCreations** [comment]
Thanks for that tip.  I am still getting the same error however.

Here is the function that is being called:

/**
 * Returns stream URL for a track.
 *
 * @param id string - track id, hyphenated is preferred, but "nid" will work for all access tracks (not uploaded ones)
 * @param callback function(err, streamUrl) - success callback
 */
PlayMusic.prototype.getStreamUrl = function (id, callback) {
    var that = this;
    var salt = pmUtil.salt(13);
    var sig = CryptoJS.HmacSHA1(id + salt, this._key).toString(pmUtil.Base64);
    var qp = {
        u: "0",
        net: "wifi",
        pt: "e",
        targetkbps: "8310",
        slt: salt,
        sig: sig
    };
	//console.log("This " + that);
	console.log(util.inspect(that, { showHidden: true, depth: null }));
	console.log("ID " + id);
    if(id.charAt(0) === "T") {
        qp.mjck = id;
    } else {
        qp.songid = id;
    }

    var qstring = querystring.stringify(qp);
    this.request({
        method: "GET",
        url: this._mobileURL + 'mplay?' + qstring,
        options: { headers: { "X-Device-ID": that._deviceId } }
    }, function(err, data, res) {
        if(res.statusCode === 302 && typeof res.headers.location === "string") {
            callback(null, res.headers.location);
        } else {
            callback(new Error("Unable to get stream url" + err), res.headers.location);
        }
    });
};


**ERROR:**

_http_outgoing.js:333
    throw new Error('"name" and "value" are required for setHeader().');
          ^
Error: "name" and "value" are required for setHeader().
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
    at new ClientRequest (_http_client.js:101:14)
    at Object.exports.request (http.js:49:10)
    at Object.exports.request (https.js:136:15)
    at PlayMusic.request (C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:63:21)
    at PlayMusic.getStreamUrl (C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:276:10)
    at C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\app.js:45:12
    at C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:307:9
    at IncomingMessage.<anonymous> (C:\Users\ctcog\Documents\Visual Studio 2015\Projects\plei_\plei_\node_modules\playmusic\play.js:86:48)
    at IncomingMessage.emit (events.js:129:20)

**Comment by CogginCreations** [comment]
Tracked it down a bit more.  Appears it is getting a 403 error from the getSettings Method so it is never creating a device.

PlayMusic.prototype.getSettings = function(callback) {
    var that = this;

    this.request({
        method: "POST",
        url: this._webURL + "services/loadsettings?" + querystring.stringify({u: 0}),
        contentType: "application/json",
        data: JSON.stringify({"sessionId": ""})
    }, function(err, body) {
		console.log("err " + err);
        if(err) return callback(new Error("error loading settings: " + err), body);
		console.log("Body: " + body);
        // loadsettings returns text/plain even though it's json, so we have to manually parse it.
        var response;
        try {
            response = JSON.parse(body);
		//console.log("response: " + response);
        } catch (e) {
            callback(new Error("error parsing settings: " + e), body);
        }
		//console.log("response: " + response);
        callback(null, response);
    });
};


**Response: err Error: 403 error from server**

If I can get this fixed I think it will fix the overall header issue.

**Comment by jamon** [comment]
Is this working for you again with the latest version?
