### ISSUE TITLE
pm.search: 404 error from server

### ISSUE THREAD

**Issue by virginielgb** [jamon/playmusic#42]
Hello,

I am trying to use the search API, and everytime I do I get an error.
My code is as follows:
```javascript
pm.init({ email: "MY_EMAIL", password: "MY_PWD" }, function () {
     pm.search("bastille lost fire", 5, function(err, data) { // max 5 results
	      if( !err ) {
	      	console.log( "OK: " + data );
	        var song = data.entries.sort(function(a, b) { // sort by match score
	            return a.score < b.score;
	        }).shift(); // take first song
	        console.log(song);
	        pm.getStreamUrl(song.track.nid, function(err, streamUrl) {
	            console.log(streamUrl);
	        });
	      }
	      else console.log( "Err: " + err );
	    }, function(message, body, err, httpResponse) {
	        console.log("Err here: " + message);
	    });
	} );
} );
```

When running that, the output is
> ```Err: Error: error getting search results: Error: 404 error from server```

I've tried to use the query url directly in my browser (https://www.googleapis.com/sj/v1.11/query?q=bastille%20lost%20fire&max-results=5) and got this

> ```
{
    "error": {
        "errors": [
        {
            "domain": "global",
            "reason": "required",
            "message": "Login Required",
            "locationType": "header",
            "location": "Authorization"
        }
    ],
    "code": 401,
    "message": "Login Required"
    }
}
```

So, through Node I get a 404, and via my browser I get a 401. I don't understand. Any idea?

**Comment by bimusiek** [comment]
You get 404 when user does not have `all access` subscription.

**Comment by virginielgb** [comment]
Oh, okay, thank you :D
