### ISSUE TITLE
Using getAllTracks doesn't show .flac songs.

### ISSUE THREAD

**Issue by 96AA48** [jamon/playmusic#53]
Hey there, 

I'm currently further developing my cli music player for Google Music using your API.
I'm currently trying to implement user uploaded song downloading.

I ran into an issue when I uploaded an album in lossless format (`.flac`), since the uploaded album doesn't show up in the big JSON datahunk that get's returned with `getAllTracks`.

Thanks in advance!

**Comment by jamon** [comment]
Unfortunately, I'm just passing that getAllTracks call straight through to google, I don't know why flac isn't showing, is it showing uploaded mp3s?  The "uploaded music" support of the library unfortunately isn't very well tested :(

**Comment by 96AA48** [comment]
Ah, damn. I've looked through some of the documentation I found in some
other Google Play Music project.
What source of documentation do you use? Maybe there's something to be
found about lossless audio.

I also wrote a function that is able to sort all of the tracks from
getAllTracks into albums. I'll try to make a pull request for it, probably
for something along the lines of getAllAlbums.

**Comment by jamon** [comment]
Since there's no real documentation, I've based my work on some of the other libraries as well as some reverse engineering I've done myself.  The python project team is super helpful, their IRC channel is a good place to ask questions if you're trying to figure stuff out.

**Comment by 96AA48** [comment]
Okay thanks for the info!
