### ISSUE TITLE
text search always returns empty results

### ISSUE THREAD

**Issue by chadkouse** [jamon/playmusic#74]
I tracked this down as far as I can -- everything else seems to work and I get no errors -- but suddenly all of my text searches started returning empty results, ala:
```
{
  "kind": "sj#searchresponse",
  "clusterOrder": [
    "5",
    "2",
    "3",
    "1",
    "7",
    "6",
    "4",
    "8"
  ]
}
```

Note: this code was working untouched in production for months.

Any ideas?  Is this happening for anyone else?

**Comment by blkqi** [comment]
I am getting the same result for every search. The issue has reproduced for me using several different accounts (both free and paid). Also reproduces using a VPN. Yet, I know for sure this is not affecting everyone. For some users, the issue appears intermittent. It does not appear to affect any endpoint except for search.

**Comment by chadkouse** [comment]
Fwiw it started intermittent for me but now is all searches

**Comment by kweiberth** [comment]
Yeah this is happening on all searches for me. I wonder if this is a bug on Google's end or if they are purposefully changing the API.

**Comment by kweiberth** [comment]
I figured out how to set up the auth calls to get the auth token and now I can make the search call in Postman. I'm seeing the `clusterOrder` response for request to https://www.googleapis.com/sj/v1.11/query?q=beatles. However, https://www.googleapis.com/sj/v1.11/query?q=beatles&ct=1 gives me a normal response with results for type 1 which are `sj#track` type. This line https://github.com/jamon/playmusic/blob/master/play.js#L339 in this repo should be adding the `ct` param for all types (albums, artists, etc), but what I *think* might be happening is that it's getting added as `ct='1,2'` with the quotes, which does not work for me in Postman.

**Comment by kweiberth** [comment]
I can confirm that the current `master` branch works great. It just needs to be published to npm so that we can pull in the necessary changes.

**Comment by jamon** [comment]
Hi guys, sorry for the slow response, and thanks for the reearch.  Would you mind giving v2.2.1 a try, I just pushed it to npm.

Thanks,
Jamon

**Comment by jamon** [comment]
As a side note, this does highlight the need for me to build out unit tests for everything, so I'm going to try to find some time to do that in the coming week or two and see if we can get a better release cycle going for the project now that so many people are using it.

**Comment by kweiberth** [comment]
No worries. I will pull in `2.2.1` tonight and confirm it fixes the issue. Unit tests would be great. Do ping me if I can help out at all. How stable is this API? @microadam, how did you know in November we needed the `ct` query param? And why did the change just go into effect on Google's end yesterday?

**Comment by jamon** [comment]
The Google API we're using is not an official one, it's reverse-engineered from the actual google apps.  That said, it's been stable for a long time, except that every once in a while something is yanked out from under us with no warning.

I'm happy to additional contributors if you're interested and have the time.  I'll get a unit test or two running and committed on a branch and we can go from there.  I think maybe I'll setup a place where people can collaborate/ask questions.  How do you (and others) feel about Discord?

**Comment by microadam** [comment]
@kweiberth By looking at how https://github.com/simon-weber/gmusicapi worked. The API this project has been using is much older than that one (their API is versioned) so I just added parameters and played around with it until it worked using that link as guidance

**Comment by kweiberth** [comment]
Interesting. Yeah I've been using this module for about a year. Thanks a ton. It has been stable like you said. They have to know external parties are hitting their APIs, no? I wish they'd have an officially supported API (but of course am thankful we have something working). I think I can find a bit of time. Seeing a couple unit tests set up will be great and then I can add some more. I've never heard of Discord. Slack would be great. Github and Github Issues might be good enough, too.

@microadam very cool, thanks for the response. I did see that library last night whilst I was trying ot debug what was wrong. I guess the `ct` parameter has been needed for some months now, though it seemed to have been working fine for me and others without `ct`. Until yesterday 😅

**Comment by chadkouse** [comment]
@kweiberth great find - fixed it for me thanks 👍

**Comment by chadkouse** [comment]
@jamon v2.2.1 works

**Comment by kweiberth** [comment]
Also, slightly off topic, I had been constructing links for Google Play Music songs by using the `nid` of the song. It seems that has changed as well. Now links to the songs use `storeId`. So now it's `'https://play.google.com/music/m/' + storeId`.

**Comment by Keavon** [comment]
Any updates on this?
