### ISSUE TITLE
Could this be made to run in the browser?

### ISSUE THREAD

**Issue by limeblack** [jamon/playmusic#77]
Serious question.

**Comment by wwwizzarrdry** [comment]
Yes it works fine in the browser. That's the only way I use this at the moment.

**Comment by limeblack** [comment]
@wwwizzarrdry what are you using for require?  Browserify?

**Comment by limeblack** [comment]
@jamon  was the issue resolvable?  I could not figure out how to to get this to run in the browser.

**Comment by wwwizzarrdry** [comment]
What exactly are you having an issue with? I set my Google oAutj to use the pure JavaScript workflow, set my my end auth and callback endpoints in the Google dashboard and jamon's code did the rest.

I made a really basic HTML page with the artist artwork as a full screen background, and a basic table
With the album art in the one cell, and all the track/album info in adjacent cells.
And since I was just returning the max track listing, made a footer row with a back, play and forward button to iterate through the Jason payload of songs.

With a little elbow grease it should be very easy to create a functional search bar and playlist generator.

**Comment by limeblack** [comment]
@wwwizzarrdry  I'm either confused or I don't think you understand my question.
I would like to run the entire playmusic library in the browser.  Many of the require statements use things that are not available to the browser that I'm aware of.

**Comment by wwwizzarrdry** [comment]
I deleted my test page a while ago, so i had whip one up.
![gpm 2017-05-19 22-31-17](https://cloud.githubusercontent.com/assets/2218144/26263836/0fa41c4a-3ce3-11e7-922b-677a1abd88a7.png)

So in my recreation I have a single file. No routing, no nothing. Just loads a static, rand song and displays the JSON payload form your library object.

The first lines of my app.js are as follows:
 `const https = require('https');
const fs = require('fs');
const PlayMusic = require('playmusic');
const options = {
   key: fs.readFileSync('/home/wwwizzarrdry/.ssh/privatekey.pem'),
   cert: fs.readFileSync('/home/wwwizzarrdry/.ssh/certificate.pem')
};`

Then I load my saved GooglePlay configuration so I dont have to keep logging in every time and making Google upset.
`// Google Music
var pm = new PlayMusic();
var myConfig = loadConfig();

//Save Config
function saveConfig (data){
    fs.writeFile('~/myGooglePlayConfig.json', data, function (err) {
        if (err) {
            console.log('There has been an error saving your configuration data.');
            console.log(err.message);
            return;
        }
        console.log('Configuration saved successfully. (~/myGooglePlayConfig.json)');
    });
};

// Load Config
function loadConfig(){
    var data = fs.readFileSync('myGooglePlayConfig.json'),
        myObj;
    try {
        myObj = JSON.parse(data);
        console.log("loadConfig:", myObj);
    } 
    catch (err) {
        console.log('There has been an error parsing your config (./myGooglePlayConfig.json)')
        console.log("loadConfig Error:", err);
        myObj = null;
    }
    return myObj;
};`

Then I initialize PlayMusic:
`pm.init({
      androidId: myConfig.droidId,
      masterToken: myConfig.mToken
}, function(err) {
     //ERROR
     if(err) console.error(err);
     //SUCCESS
     getTracks();
})`

Finally I load a random track:
`// Get a Random Song
function getRandomSong(library){
        var obj_keys = Object.keys(library.data.items);
        var ran_key = obj_keys[Math.floor(Math.random() * obj_keys.length)];
        gpm.rand_song = library.data.items[ran_key];
        getStreamUrl(gpm.rand_song);
};`

Now just plop all the pieces in into your template and you're done.
Or just write the html directly like i did for the test page (lol):
`var artist, album, title, year, genre, albumArt, artistArt, stream, html;
function buildListing(track) {
    artist = track.artist;
    album = track.album;
    title = track.title;
    year = track.year;
    genre = track.genre;
    albumArt = track.albumArtRef[0].url;
    artistArt = track.artistArtRef[0].url;
    stream = track.url;

    html = "<table style='background: rgba(255,255,255,0.45); padding: 16px;'>" +
        "<tfoot><tr><th colspan='3' align='left'>Genre: "+ genre +"</th></tr></tfoot>" +
        "<tbody>" +
        "<tr><th rowspan='6'><img src='"+ albumArt +"' width='250px'/></th></tr>" +
        "<tr><th>Artist: </th><td align='left'>"+ artist +"</td></tr>" +
        "<tr><th>Album: </th><td align='left'>"+ album +"</td></tr>" +
        "<tr><th>Year: </th><td align='left'>"+ year +"</td></tr>" +
        "<tr><th>Track: </th><td align='left'>"+ title +"</td></tr>" +
        "<tr>" +
            "<th colspan='3'>" +
                "<audio controls>" +
                    "<source src='"+ stream + "' type='audio/mpeg'>" +
                    "Your browser does not support the audio element." +
                "</audio>" +
            "</th>"+
        "</tr>" +
        "</tbody>" +
    "</table>"; 
};`

**Comment by wwwizzarrdry** [comment]
I'm not sure what else you might be implying by, "make this work in a browser"

**Comment by limeblack** [comment]
@wwwizzarrdry yeah we are not talking about the same thing.  I want to this without running node.js at all.

Read up on http://browserify.org/
