### ISSUE TITLE
PlayMusic.prototype.removePlayListEntry doesn't remove entry

### ISSUE THREAD

**Issue by stdemon** [jamon/playmusic#79]
PlayMusic.prototype.removePlayListEntry method returns success callback, however entry still can be fetched via PlayMusic.prototype.getPlayListEntries with no notification that entry was already deleted.
Is there some way to delete entry?
TIA

**Comment by limeblack** [comment]
bump

**Comment by stdemon** [comment]
Sorry, my fault.
It works.
