### ISSUE TITLE
addTrackToPlayList return 200 status, but doesn't work in general

### ISSUE THREAD

**Issue by iKethavel** [jamon/playmusic#84]
Hi, I'm trying to add tracks to my playlist over this method from your API, but it doesn't work.
On response, I've had 200 status, but the playlist is empty...

<details> 
  <summary>Response </summary>
{
mutate_response: [
{
id: "bd227133-f856-358b-86e3-cc70f83ad83f",
client_id: "1436e050-6635-11e7-b9bb-650ca29c6b18",
response_code: "OK"
},
{
id: "60b34bb2-2819-3da9-bc75-6403ddf65a4f",
client_id: "1436e051-6635-11e7-b9bb-650ca29c6b18",
response_code: "OK"
},
{
id: "8bcb0aab-af92-3fc6-8301-10f1eefff801",
client_id: "1436e052-6635-11e7-b9bb-650ca29c6b18",
response_code: "OK"
}
]
}
</details>

**Comment by JonBons** [comment]
I was running into the same issue but I switched my call from using the track's nid to the storeId property and it appears to be working now.
