### ISSUE TITLE
Unable to use in reactjs app

### ISSUE THREAD

**Issue by Belisarith** [jamon/playmusic#91]
Trying to use API in a reactJs App.

`
import PlayMusic from "playmusic";

const GoogleMusic = {
  init() {
    let pm = new PlayMusic();
    pm.login({ email: "emai@email.com", password: "test" }, function(err,rsp) {});
  }
};

export default GoogleMusic;
`

However, even the login already fails with the following error message:
"RangeError: offset is not uint"
coming from encryptLogin.js

**Comment by awongCM** [comment]
Works fine for me.  I had no issues. I'm doing this from nodejs end though.

```
pm.login({ email: "email@email.com", password: "testpassword"}, function (err, data) {
      if(err) res.send({error: err});
      res.json({message: 'Google Music Account Logged In!', data: data});
    });
```
Have you tried writing out error/response callback handling in your code, and debug it from there?  ie for eg

```
// In your callback
if (err)  {console.log("Error: ", err); return;}
console.log("Response", rsp);
```

**Comment by Belisarith** [comment]
Tried it from node directly, too. Here it is working.
However in a react app I get the following error:

`Uncaught RangeError: offset is not uint
    at checkOffset (index.js:1097)
    at Uint8Array.readInt32BE (index.js:1229)
    at decompose (encryptLogin.js:37)
    at ./node_modules/playmusic/lib/encryptLogin.js.module.exports (encryptLogin.js:48)
    at PlayMusic../node_modules/playmusic/play.js.PlayMusic.login (play.js:196)`

And a uint array of size 139 is written to the console.
The console.log statement comes from the encryptLogin.js (line 35). The following function, where the "buf" is written out.

`function decompose(_buf) {
  console.log(_buf);
  var buf = new Uint8Array(_buf);
  var i = _buf.readInt32BE();
  var mod = Buffer.from(buf.buffer, 4, i);
  var j = _buf.readInt32BE(i + 4);
  var exp = Buffer.from(buf.buffer, i + 8, j);
  return getPem(mod.toString("base64"), exp.toString("base64"));
}`

Is it possible, that the reason is that it the programm is now running in the browser?

**Comment by jamon** [comment]
I've never tested from a browser directly--though some others have said that it was successful.  I'm actually quite surprised that anyone was able to get it to work from a browser directly, honestly.  Depending on what kind of app you're building, it's probably best to route through a node service.

**Comment by awongCM** [comment]
Come to think of it, I'm surprised by this development as well.

Never tried implementing this service within browser environment myself.  I don't see how is that possible.

How I implemented the library for my personal pet project is that I first created a RESTFUL API server that is simply a wrapper around the library's core functionality (running in node/express, of course).  Like any typical RESTFUL API server, you should come up with simple abstractions  which describe meaningful named routes and resources, and map to their corresponding library's functionality.  

For eg in my server.js, I do the following.

```
//API setup
var express    = require('express');        
var app        = express();                
var bodyParser = require('body-parser');
var PlayMusic  = require('playmusic');
var pm = new PlayMusic();

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
var port = process.env.PORT || 3000;

// setup the following routes
var router = express.Router();

//Login end point
router.route('/login').get(function (req, res) {
    const {email, password} =  req.params;
    pm.login({ email: email, password: password}, function (err, credentials) {
      if(err) res.send({error: err});
      res.json({message : "Google Play login successfully!", credentials: credentials});
    });
  });

//Songs end point
router.route('/songs').get( function (req, res) {
    pm.getAllTracks( function (err, library) {
      if(err) res.send({error: err});
      var songs = library.data.items;
      res.json({message : 'All my personal songs fetched!', songs: songs});
    });
});

//register API ROUTES
app.use('/api', router);
app.listen(port);
console.log('Google Music API Server listening on port ' + port);
```
Next, on the front end, I create a class or module that's responsible for consuming this RESTFUL API service, using the endpoints I made previously.  For eg. in React, you could do something like

```
//api.js
import axios from 'axios';

export const EMAIL = 'email@email.com';
export const PASSWORD = 'testpassword';

//assuming you use Babel configuration for this.
export default class GoogleMusic {
   static resquestLogin() {
     return axios({
       method: 'get'
       url: 'http://localhost:3000/api/login'
       data: {email: EMAIL, password: PASSWORD}
     });
   }
   
   static getSongs() {
     return axios({
        method: 'get',
        url: 'http://localhost:3000/api/songs'
     })
   }
}
```

Elsewhere in your react component
```
import {GoogleMusic} from 'api';

class MusicWidget extends Component {
  constructor(props){}

  login() {
      GoogleMusic.requestLogin()
      .then(res => console.log(res))
      .catch(err => console.log(err);
  }
  loadSongs() {
       GoogleMusic.getSongs()
       .then(data => console.log(data));
       .catch(err => console.log(err));
  }
}

export default MusicWidget;
```

Again - with simple abstractions (and with proper encapsulation in place) you got yourself a working front-music app that fetches the correct music stream uri services respectively from Google Play.

Hope this helps you.

**Comment by Belisarith** [comment]
Thanks all for the input.
I will follow your suggestions awongCM. I will would be interested however, how someone got to run the library in the browser directly.
